name: CI - Tag Release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml

  deploy_production:
    needs: ci
    runs-on: ubuntu-22.04
    name: Deploy to Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps (Production)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SEA_080BC3503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src/Gui/sp-gui.html/sp-gui-angular/dist/gui/browser"
          api_location: "/src/Gui/sp-gui.html/sp-gui-angular/api"
          output_location: ""
          skip_app_build: true

  create_release_notes:
    needs: deploy_production
    runs-on: ubuntu-22.04
    name: Create Release Notes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag version
        id: tag_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          release_name: Release ${{ steps.tag_version.outputs.version }}
          body: |
            Release ${{ steps.tag_version.outputs.version }}

            Live at: https://orange-sea-080bc3503.azurestaticapps.net/
          draft: false
          prerelease: false
